-------------------------------------------------------------------------------
Test set: EnemyFactoryTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.022 s <<< FAILURE! -- in EnemyFactoryTest
EnemyFactoryTest.testCreateUnknownEnemyThrowsException -- Time elapsed: 0.013 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: <manfrinmarco.security.GameException> but was: <java.lang.IllegalArgumentException>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3115)
	at EnemyFactoryTest.testCreateUnknownEnemyThrowsException(EnemyFactoryTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
Caused by: java.lang.IllegalArgumentException: Nemico non trovato: drago
	at manfrinmarco.entities.EnemyFactory.createEnemy(EnemyFactory.java:31)
	at EnemyFactoryTest.lambda$testCreateUnknownEnemyThrowsException$0(EnemyFactoryTest.java:24)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more

